services:
    db: # MariaDB container
        container_name: db
        image: mariadb:11.5.2
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - ./db:/var/lib/mysql
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        networks:
            - psnet
        # platform: linux/x86_64 # Apple Silicon Macs only
    ps: # PrestaShop container
        container_name: ps
        image: prestashop/prestashop:1.7.8
        restart: unless-stopped
        environment:
            PS_DEV_MODE: 1
            DB_SERVER: db
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWD: ${DB_PASSWORD}
            PS_INSTALL_AUTO: 0
        ports:
            - 80:80   # HTTP
            - 443:443 # HTTPS
        volumes:
            - ./src:/var/www/html
            - ./ssl:/etc/ssl/certs
            - ./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            - psnet
        depends_on:
            - db
        # platform: linux/x86_64 # Apple Silicon Macs only
        command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    pma: # phpMyAdmin container
        container_name: pma
        image: phpmyadmin/phpmyadmin:5.2.1
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_PORT: 3306
        ports:
            - 8081:80
        networks:
            - psnet
        # platform: linux/x86_64 # Apple Silicon Macs only
networks:
    psnet: