<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWaarwl9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWaarwl9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWaarwl9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWaarwl9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWaarwl9\appDevDebugProjectContainer([
    'container.build_hash' => 'Waarwl9',
    'container.build_id' => '0f096bc4',
    'container.build_time' => 1731351883,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWaarwl9');
