<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3nvugl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3nvugl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP3nvugl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP3nvugl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP3nvugl\appDevDebugProjectContainer([
    'container.build_hash' => 'P3nvugl',
    'container.build_id' => '80e4bd13',
    'container.build_time' => 1731527078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP3nvugl');
