<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmb26mp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmb26mp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHmb26mp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHmb26mp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHmb26mp\appDevDebugProjectContainer([
    'container.build_hash' => 'Hmb26mp',
    'container.build_id' => '944baf92',
    'container.build_time' => 1732365829,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmb26mp');
