<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGqrmx2q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGqrmx2q/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGqrmx2q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGqrmx2q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGqrmx2q\appProdProjectContainer([
    'container.build_hash' => 'Gqrmx2q',
    'container.build_id' => '291fc7aa',
    'container.build_time' => 1731412044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGqrmx2q');
