<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGflzted\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGflzted/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGflzted.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGflzted\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGflzted\appProdProjectContainer([
    'container.build_hash' => 'Gflzted',
    'container.build_id' => 'a8c6b609',
    'container.build_time' => 1730972509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGflzted');
