<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXulyvz5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXulyvz5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXulyvz5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXulyvz5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXulyvz5\appProdProjectContainer([
    'container.build_hash' => 'Xulyvz5',
    'container.build_id' => 'cecabb2e',
    'container.build_time' => 1733142248,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXulyvz5');
