name: Build Docker Image

on:
  push:
    branches:
      - main
      - master
      - image_creation
      - dev
      
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-container:latest .

      - name: Verify Docker image
        run: |
          docker images | grep my-container
